version: "3"

services:
  postgres:
    container_name: calendar_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrator:
    container_name: migrator
    build:
      context: ..
      dockerfile: ./build/migrator/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - "../configs:/app/configs"
      - "../migrations:/app/migrations"
    command: -config /app/configs/config.toml -dir /app/migrations up

  calendar:
    container_name: calendar
    build:
      context: ..
      dockerfile: ./build/calendar/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - migrator
    volumes:
      - "../configs:/app/configs"
    command: -config=/app/configs/config.toml

volumes:
  db_data: