version: "3"

services:
  tests:
    container_name: calendar_tests
    build:
      context: ..
      dockerfile: ./build/tests/Dockerfile
    depends_on:
      - calendar
      - scheduler
      - sender

  postgres:
    container_name: postgres_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data