version: "3"

services:
  tests:
    container_name: calendar_tests
    build:
      context: ..
      dockerfile: ./build/tests/Dockerfile
    depends_on:
      - calendar
      - scheduler
      - sender