[logger]
level = "DEBUG"
file = "stdout"

[storage]
storage_type = "psql"
user = "calendar"
password = "calendar"
db = "calendar"
host = "postgres"
port = "5432"

[http]
host = "0.0.0.0"
port = "8080"

[grpc]
host = "0.0.0.0"
port = "9000"

[amqp]
uri = "amqp://guest:guest@rabbit:5672"
queue = "calendar"

[scheduler]
notify_before = "10m"
period = "1h"