[logger]
level = "DEBUG"
file = "stdout"

[storage]
storage_type = "psql"
user = "postgres"
password = "postgres"
db = "calendar"
host = "localhost"
port = "5432"

[server]
host = "127.0.0.1"
port = "8080"