[logger]
level = "DEBUG"
file = "stdout"

[storage]
storage_type = "psql"
user = "postgres"
password = "postgres"
db = "calendar"
host = "localhost"
port = "5432"

[http]
host = "127.0.0.1"
port = "8080"

[grpc]
host = "127.0.0.1"
port = "9000"

[amqp]
uri = "amqp://guest:guest@localhost:5672"
queue = "calendar"

[scheduler]
remind_before = "1h"