[logger]
level = "DEBUG"
file = "stdout"

[storage]
storage_type = "psql"
user = "postgres"
password = "postgres"
db = "calendar_test"
host = "172.24.224.1"
port = "5433"

[http]
host = "127.0.0.1"
port = "8080"

[grpc]
host = "127.0.0.1"
port = "9000"

[amqp]
uri = "amqp://guest:guest@localhost:5672"
queue = "calendar"

[scheduler]
notify_before = "10m"
period = "1h"